#!/system/bin/sh
#

# ext4
insmod /system/lib/modules/jbd2.ko
insmod /system/lib/modules/ext4.ko

# bluetooth
insmod /system/lib/modules/rfkill.ko
insmod /system/lib/modules/bluetooth.ko
insmod /system/lib/modules/rfcomm.ko
insmod /system/lib/modules/bnep.ko
insmod /system/lib/modules/hidp.ko
insmod /system/lib/modules/btusb.ko

# network
insmod /system/lib/modules/tun.ko
insmod /system/lib/modules/tcp_veno.ko
echo veno > /proc/sys/net/ipv4/tcp_congestion_control

# usb serial
insmod /system/lib/modules/cp210x.ko
insmod /system/lib/modules/pl2303.ko

# gamepads
insmod /system/lib/modules/xpad.ko
insmod /system/lib/modules/hid-gaff.ko
insmod /system/lib/modules/hid-pl.ko
insmod /system/lib/modules/hid-sony.ko

# misc
insmod /system/lib/modules/uinput.ko

